### ISSUE TITLE
Obsolete?

### ISSUE THREAD

**Issue by davelab6** [OpenTechStrategies/openstv#1]
The last commit was a few years ago.... is this now obsolete software? What are good and actively maintained replacements?

**Comment by Tyrand** [comment]
I wouldn't consider this obsolete at all - It's an abandoned version of the software because of the creator's decision to change license.

I still use this software often for community elections and it works fine since all I need is a STV counter.

As for replacements I can't recommend any since I haven't looked to replace this.

**Comment by davelab6** [comment]
> because of the creator's decision to change license

But no one is fixing any bugs or adding features since then? or is it bug free and feature complete?

**Comment by davelab6** [comment]
Thanks for confirming it is still working fine though, that's helpful for me as I'm seeking out a voting tool for www.sugarlabs.org :)

**Comment by Tyrand** [comment]
As far as I know this isn't getting updated.

I presume the main aim for this upload was just to keep the program readily available - Which is all I needed.

As for bugs and features I haven't noticed any crashing bugs - It's more of an issue just making sure the voting ballots are 100% accurate - I create my own ballot files manually since the built-in ballot editor is very slow.

I assume new features (like more obscure STV methods) have been integrated into the latest version of this program but the creator has already started to sell online STV counting services - Basically discontinuing the program.

**Comment by kfogel** [comment]
Hey, @davelab6 .  The canonical home for this archived version of OpenSTV is actually https://github.com/Conservatory/openstv/ (however, that tree is the same as the one here.)  To the best of my knowledge, the software is not being maintained; at the very least, no one is maintaining the version in the Conservatory.  The README.md gives the details of the code's history.

If you're looking for voting software, I think the places to start are probably:

* Helios Voting: https://vote.heliosvoting.org/
* Condorcet Internet Voting Service: http://civs.cs.cornell.edu/
* Apache STeVe (https://steve.apache.org/)
* https://github.com/conservancy/voting (lists a bunch of other software too)
* https://github.com/mdipierro/evote
* https://github.com/Conservatory/openstv (including here so you have a complete list)

One of the first three is probably your best bet.  There may be other places offering Ranked Choice / STV as SaaS now; I haven't looked around too much.  I like that Helios is open source, but, alas, that is not by itself evidence that it is the best UI/UX or best implementation of the algorithm, etc, of course.

I've used Apache STeVe in a test Board election at the Apache Software Foundation.  The user interface is pretty good, and it supports the "Single Transferable Vote" method as well as some others.  (Oddly, it seems not to have direct support for Approval Voting, but that ought to be very easy to add if someone wants it, since implementation-wise it's really a subset of the STV algorithm anyway.)

As for voting method: for most purposes, Score Voting, Approval Voting,  or STV are probably fine.  If you want more resources, this tweet (in which I got engaged in a discussion with some people about the advantages of Score Voting) is a good starting point: https://twitter.com/kfogel/status/705857077768376320.  It's a complex question, and the right choice depends on what kinds of outcomes you're going for.

**Comment by davelab6** [comment]
@kfogel awesome!!! Thanks for the detailed reply :)

**Comment by edulix** [comment]
Hi everyone: I just wanted to share that we at Agora Voting provide a open source software secure voting tool, and maintain a fork of openstv here: https://github.com/agoravoting/agora-tally/tree/next/agora_tally/ballot_counter

**Comment by davelab6** [comment]
@edulix wow thats awesome :D I added agora to the top of the list on my PR

**Comment by kfogel** [comment]
I've merged everything over to the main repository at https://github.com/Conservatory/openstv now, and set the default branch here to a new branch named `frozen` that just points people over to the Conservatory version, which is canonical.  Thanks, @davelab6 and @edulix!

**Comment by davelab6** [comment]
Thanks Karl!
